### ISSUE TITLE
Is there any way to cancel the timer that started by TimeCircularCountdown?

### ISSUE THREAD

**Issue by jdurga** [MattisBrizard/circular_countdown#3]
I use TimeCircularCountdown to display a countdown timer(60sec) and when build of screen is finished and the user takes some action and called set_state() to display another countdown timer(10sec) in place of 60sec timer, but It's not happening and callback is called on expiry of 60sec timer.
Is there any way to access the timer instance created by  _TimeCircularCountdownState, to cancel (timer.cancel()) before calling another instance of TimeCircularCountdown?

**Comment by MattisBrizard** [comment]
Hi @jdurga, thanks for opening an issue.
In fact it is not possible to access the timer instance, but I fixed a bug resulting in not displaying the new `TimeCircularCountdown` when some properties have changed.

You can find the changelog here : https://pub.dev/packages/circular_countdown/changelog#121---16072020
Tell me if this new version is fixing your issue. 😄

**Comment by MattisBrizard** [comment]
Hi @jdurga, are you still facing the issue ?

**Comment by MattisBrizard** [comment]
Hi, I'm closing this issue for now, feel free to re-open one if needed.
