### ISSUE TITLE
Pause the countdown

### ISSUE THREAD

**Issue by myThorsten** [MattisBrizard/circular_countdown#6]
Hello again :)

as the title says, is there a way to pause a running countdown?
And later continue it.

Thank you for implementing null-safety, btw 👍

**Comment by MattisBrizard** [comment]
Hi @myThorsten, sorry for the late response.
It's currently not possible with the `TimeCircularCountdown`. 
What you can do is implementing the timer logic by your side and use the classic `CircularCountdown` with it.

I'm currently trying to separate the timer logic in an object, will tell you when it's ready.

**Comment by MattisBrizard** [comment]
Hi @myThorsten, i just published a new package: timer_controller
Github: https://github.com/MattisBrizard/timer_controller
Pub: https://pub.dev/packages/timer_controller

This can be used in addition to circular_countdown to have more fine-grained controls about the timer. And easily deal with a single timer object across differents screens for example.

I'm closing this issue, if you need help to build something with this new package, just tell me and I'll try to help you :)
